### PR TITLE
Fixed StringBuffer warning by using StringBuilder

### PR DESCRIPTION
**Pull request by Jearil**
The default project won't compile when a warning occurs, which was
happening due to the use of StringBuffer rather than StringBuilder.
Switched to StringBuilder and the compilation works.

Previously if you followed the instructions at https://cloud.google.com/java/getting-started/using-forms, you'd get the following. This fixes it.

```
$ mvn compile
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.example.getstarted:bookshelf-2 >-----------------
[INFO] Building bookshelf-2 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.3:prepare-agent (default) @ bookshelf-2 ---
[INFO] argLine set to -javaagent:/home/jearil/.m2/repository/org/jacoco/org.jacoco.agent/0.8.3/org.jacoco.agent-0.8.3-runtime.jar=destfile=/home/jearil/Projects/getting-started-java/bookshelf/2-structured-data/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ bookshelf-2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jearil/Projects/getting-started-java/bookshelf/2-structured-data/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ bookshelf-2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to /home/jearil/Projects/getting-started-java/bookshelf/2-structured-data/target/bookshelf-2-1.0-SNAPSHOT/WEB-INF/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/jearil/Projects/getting-started-java/bookshelf/2-structured-data/src/main/java/com/example/getstarted/util/DatastoreSessionFilter.java:[136,25] [JdkObsolete] StringBuffer performs synchronization that is usually unnecessary; prefer StringBuilder.
    (see https://errorprone.info/bugpattern/JdkObsolete)
  Did you mean 'StringBuilder names = new StringBuilder();'?
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.500 s
[INFO] Finished at: 2019-11-06T09:06:01-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project bookshelf-2: Compilation failure
[ERROR] error: warnings found and -Werror specified
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

### CODE REVIEW

**Comment by Jearil** [comment]
@googlebot I signed it!

**Comment by Jearil** [comment]
Updating this because while the first commit fixed mvn compile, this one fixes mvn jetty:run-exploded (there were warnings in UserJourneyIT.java)

**Comment by lesv** [comment]
@dpebot merge when green

**Comment by dzlier-gcp** [comment]
@dpebot Merge when green.

**Pull request merged**
