### PR TITLE
Spring Boot example

### PR DESCRIPTION
**Pull request by saturnism**
A quick example on Spring Boot Helloworld with App Engine MVM.

### CODE REVIEW

**Comment by tswast** [comment]
LGTM

**Comment by lesv** [comment]
Please don't yet merge.

**Comment by lesv** [comment]
Please don't merge yet.

On Tue, Feb 23, 2016 at 9:47 AM, Tim Swast <notifications@github.com> wrote:

> LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/getting-started-java/pull/23#issuecomment-187814155>
> .
>



-- 


*  •  **Les Vogel*
*  •  *Cloud Developer Relations
*  •  *lesv@google.com
*  •  *+1-4 <%2B1-650-338-7103>08-676-7023

**Comment by lesv** [comment]
Ray - could you fix the spacing - we are using the Google Java style guide. (2 spaces indents - no tabs).  https://google.github.io/styleguide/javaguide.html

**Comment by saturnism** [comment]
oops, sorry didn't realize that. the code was generated from starter.spring.io and it was using \t by default. replaced \t with two spaces. PTAL.

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
Thanks

**Pull request merged**
