### PR TITLE
Initial selenium test.

### PR DESCRIPTION
**Pull request by jerjou**
Just a test for now to make sure travis passes...

### CODE REVIEW

**Comment by jerjou** [comment]
Hey guys-

Initial take on selenium tests for bookshelf. It's passing on chrome (after some fenagling with the travis image), though not on firefox or in circle-ci yet. I figure we can get this in first, and fix firefox and circle-ci later (since circle-ci is broken anyway ^_^ - this PR at least gets it a little bit closer to working, I think).

**Comment by jerjou** [comment]
Also, FYI the updates to the various pom.xml's somehow ended up running the `verify` step on a bunch of dirs that it previously wasn't being run on -_-; So there are a couple style fixes in this PR as well to address breakages that were already there but weren't being tested.

**Comment by jerjou** [comment]
Updated comments to explain why ignoring is okay.

**Comment by lesv** [comment]
@jerjou Could you look into circle?

```
E: Unable to locate package chromium-chromedriver

sudo apt-get update; sudo apt-get install chromium-chromedriver returned exit code 100

Action failed: sudo apt-get update; sudo apt-get install chromium-chromedriver
```

**Comment by jerjou** [comment]
Yeah, I'm looking into getting circle working, but don't want to block this PR on it, since circle wasn't working before this either :-)

**Pull request merged**
