### PR TITLE
Prepare for 2.0 release of plugins

### PR DESCRIPTION
**Pull request by loosebazooka**
Specifically for 2.0 appengine (cloud sdk based) plugins

- limit current gradle plugin to 1.+ (instead of +), so we can
  gracefully update to 2.0 (or 2.+).

- add in package requirement for running appengine:<goal> on maven,
  get users in the habit of using non-forked plugin goals.

### CODE REVIEW

**Comment by loosebazooka** [comment]
ping @llatif, we've release 2.0.0-rc1 for both maven and gradle.

**Comment by loosebazooka** [comment]
Hrmm... I might need to clean this up a lot more now.

**Comment by lesv** [comment]
@loosebazooka Should we close this or something else?

**Comment by loosebazooka** [comment]
you know what, I'll work on this today. I'll clean it up.

**Comment by loosebazooka** [comment]
actually I'll just take this down.

**Pull request closed without merging**
