### PR TITLE
Modified bookshelf.bucket property to use myBucketName instead of using projectId

### PR DESCRIPTION
**Pull request by frankyn**
The current instruction at https://cloud.google.com/java/tutorials/bookshelf-on-compute-engine doesn't expect/suggest the user should use the project-id as the bucket name. So I updated the value of the `bookshelf.bucket` to be `myBucketName` instead.

### CODE REVIEW

**Comment by jabubake** [comment]
Looking at the instructions in the README and pom.xml where we use the project id in the sql connection string : looks like we should be asking users to set the project id ? We could use the project id as the bucket name or provide that as a separate param.

**Comment by frankyn** [comment]
Are you referring to this part?
```
  <sql.dbName>bookshelf</sql.dbName>                        <!-- A reasonable default -->
  <!-- Instance Connection Name - project:region:dbName -->                       
  <!-- -Dsql.instanceName=localhost to use a local MySQL server --> 
  <sql.instanceName>${projectID}:us-central1:${sql.dbName}</sql.instanceName> 
  <sql.userName>root</sql.userName>                         <!-- A reasonable default -->
  <sql.password>myRootPassword1234</sql.password> <!-- -Dsql.password=myRootPassword1234 -->
```

**Comment by frankyn** [comment]
Updated PR to reflect conversation with @jabubake and @lesv last comment.

**Comment by lesv** [comment]
Circle won't pass, ok to merge as admin.

**Pull request merged**
