### PR TITLE
Switch from envVars to Properties

### PR DESCRIPTION
**Pull request by lesv**
1. move from env vars in app.yam to bookshelf.properties

### CODE REVIEW

**Comment by lesv** [comment]
@shun-fan PTAL - even though I'm going to LGTM myself.
@tswast FYI
Note I also moved index.yaml to root.

**Comment by lesv** [comment]
LGTM

**Comment by tswast** [comment]
LGTM

**Comment by lesv** [comment]
Thanks tim - there was a bug in this I used a lowercase -d instead of -D - fixed on Shun's next PR.

**Pull request merged**
